// Mocks generated by Mockito 5.0.15 from annotations
// in flutter_cars_app/test/domain/usecases/car/get_car_list_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_cars_app/core/errors/failure.dart' as _i5;
import 'package:flutter_cars_app/domain/entities/car/car.dart' as _i6;
import 'package:flutter_cars_app/domain/repositories/car_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [CarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarRepository extends _i1.Mock implements _i3.CarRepository {
  MockCarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Car>>> getCarList() =>
      (super.noSuchMethod(Invocation.method(#getCarList, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Car>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Car>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Car>>>);
  @override
  String toString() => super.toString();
}
